version: "3.7"
services:
  pubsub:
    container_name: pubsub
    build: https://github.com/ochom/pubsub.git#main
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./data:/var/lib/rabbitmq
