version: "3"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq-custom
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./data:/var/lib/rabbitmq

volumes:
  rabbitmq:
