version: "3.7"
services:
  rabbitmq:
    container_name: rabbitmq
    build: .
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin2020
    volumes:
      - ./data:/var/lib/rabbitmq
